<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "EXTENSION_KEY_SC"
 *
 * Auto generated by the Tollwerk TYPO3 Docker images (https://github.com/tollwerk/docker-typo3)
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['EXTENSION_KEY_SC'] = [
    'title'            => 'Project: PROJECT_NAME',
    'description'      => 'Custom features for PROJECT_NAME',
    'category'         => 'misc',
    'author'           => 'AUTHOR_NAME',
    'author_email'     => 'AUTHOR_EMAIL',
    'state'            => 'alpha',
    'internal'         => '',
    'uploadfolder'     => '0',
    'createDirs'       => '',
    'clearCacheOnLoad' => 0,
    'version'          => '1.0.0',
    'constraints'      => [
        'depends'   => [
            'typo3'               => 'TYPO3_VERSION_TAG-',
            'tw_base'             => '*',
            'tw_componentlibrary' => '*',
        ],
        'conflicts' => [],
        'suggests'  => [],
    ],
];
